# Generated by Django 3.2.9 on 2023-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='file_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
