# Generated by Django 3.2.9 on 2023-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230812_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Imagem'),
        ),
    ]
